CREATE TABLE users (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    password TEXT NOT NULL,
    display_name TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    username TEXT NOT NULL
);