CREATE TABLE points (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    contest_id INTEGER NOT NULL,
    points INTEGER NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    win_id INTEGER,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);